// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Sbb1n1oUL-mqBd8PD1fUn1SFMYbF96k',
    appId: '1:412809400251:web:904a14c24f5d779d427e9e',
    messagingSenderId: '412809400251',
    projectId: 'zoom-clone-74a95',
    authDomain: 'zoom-clone-74a95.firebaseapp.com',
    storageBucket: 'zoom-clone-74a95.firebasestorage.app',
    measurementId: 'G-QGJ9Q3ZYBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZRWLEDGjG9KoS88a8VC6wiCSo_notJk',
    appId: '1:412809400251:android:01a38342411fa943427e9e',
    messagingSenderId: '412809400251',
    projectId: 'zoom-clone-74a95',
    storageBucket: 'zoom-clone-74a95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXfMHs1iLYuEUOtHxcUTHtylUofDN2fYs',
    appId: '1:412809400251:ios:c713566fab54e87e427e9e',
    messagingSenderId: '412809400251',
    projectId: 'zoom-clone-74a95',
    storageBucket: 'zoom-clone-74a95.firebasestorage.app',
    iosBundleId: 'com.example.zoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXfMHs1iLYuEUOtHxcUTHtylUofDN2fYs',
    appId: '1:412809400251:ios:c713566fab54e87e427e9e',
    messagingSenderId: '412809400251',
    projectId: 'zoom-clone-74a95',
    storageBucket: 'zoom-clone-74a95.firebasestorage.app',
    iosBundleId: 'com.example.zoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Sbb1n1oUL-mqBd8PD1fUn1SFMYbF96k',
    appId: '1:412809400251:web:5e8c91104421c961427e9e',
    messagingSenderId: '412809400251',
    projectId: 'zoom-clone-74a95',
    authDomain: 'zoom-clone-74a95.firebaseapp.com',
    storageBucket: 'zoom-clone-74a95.firebasestorage.app',
    measurementId: 'G-D74JZZQMYX',
  );
}
